config:
    target: 'http://localhost:4000'
    processor: './random-users-payload.js'
    phases:
        - duration: 10
          arrivalRate: 2
        - duration: 60
          arrivalRate: 5
          rampTo: 20

scenarios:
    - name: 'Load tests'
      flow:
          - post:
                url: '/login'
                json:
                    login: 'admin'
                    password: 'admin'
                capture:
                    - json: '$.token'
                      as: token
                expect:
                    - statusCode: 201

          - function: 'generateRandomPayload'
          - post:
                url: '/users'
                json: '{{ payload }}'
                capture:
                    - json: '$.id'
                      as: userId
                headers:
                    Authorization: 'Bearer {{ token }}'
                expect:
                    - statusCode: 201

          - get:
                url: '/users/{{ userId }}'
                headers:
                    Authorization: 'Bearer {{ token }}'
                expect:
                    - statusCode: 200

          - function: 'generateRandomPayload'
          - put:
                url: '/users/{{ userId }}'
                json: '{{ payload }}'
                headers:
                    Authorization: 'Bearer {{ token }}'
                expect:
                    - statusCode: 200

          - delete:
                url: '/users/{{ userId }}'
                headers:
                    Authorization: 'Bearer {{ token }}'
                expect:
                    - statusCode: 200

          - get:
                url: '/users'
                headers:
                    Authorization: 'Bearer {{ token }}'
                expect:
                    - statusCode: 200
