version: '3'
services:
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        container_name: docker-task
        depends_on:
            - postgres
        environment:
            - PORT=${PORT}
    postgres:
        build: ./database/
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        container_name: docker-task-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}